config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do

  authenticate :user, -> (user) { user.is_admin? } do
    mount Sidekiq::Web => 'admin/sidekiq'
  end

  devise_for :users, :controllers => { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :donate_events

  root "home#index"

  mount ApiRoot => ApiRoot::PREFIX
end

app/models/api_access_token.rb
class ApiAccessToken < ApplicationRecord
  belongs_to :user

  def regenerate_keys!
    return if enabled?
    begin
      self.key = SecureRandom.urlsafe_base64(30).tr('_-', 'xx')
      self.enable = true
    end while ApiAccessToken.where(key: key).any?
  end

  def enabled?
    enable
  end

  def revoke!
    return if !enabled?
    self.update_attribute(:enable, false)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donate_event.rb
class DonateEvent < ApplicationRecord
  belongs_to :user
  has_many :lotteries

  enum status: {
    enable: 0,
    disable: 1
  }

  before_create :generate_token

  after_commit :broadcast_goal!

  private

  def generate_token
    self.token = SecureRandom.hex(6)
  end

  def broadcast_goal!
    ActionCable.server.broadcast("donate_goal_channel_#{token}", goal_amount: goal_amount, total_amount: total_amount)
  end
end

app/models/donate_history.rb
class DonateHistory < ApplicationRecord
  belongs_to :user

  after_create :update_event!

  has_one :lottery_result

  private

  def update_event!
    event = user.donate_events.enable.last

    return if event.blank?

    lotteries = event.lotteries

    # 先抽獎，在更新 Event，避免前端被 boradcast 之後資料的時間差
    if lotteries.present?
      min_number = lotteries.pluck(:id).min
      max_number = lotteries.pluck(:id).max

      win_lottery = lotteries.find(rand(min_number..max_number))

      create_lottery_result!(lottery: win_lottery, item: win_lottery.item)
    end

    total_amount = DonateHistory.where(user: user, donate_at: event.created_at..event.end_after.end_of_day).sum(:amount_micros) / 1000000

    event.update!(total_amount: total_amount)
  end

  def amount
    amount_micros / 1000000
  end
end

app/models/identity.rb
class Identity < ApplicationRecord
  belongs_to :user

  validates_presence_of :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider

  def self.find_for_oauth(auth)
    find_or_create_by(uid: auth.uid, provider: auth.provider)
  end
end

app/models/lottery.rb
class Lottery < ApplicationRecord
  belongs_to :donate_event
end

app/models/lottery_result.rb
class LotteryResult < ApplicationRecord
  belongs_to :donate_history
  belongs_to :lottery
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :omniauthable, :omniauth_providers => [:google_oauth2]

  has_many :donate_events
  has_many :donate_histories
  has_many :identities

  has_one :api_access_token

  before_create :generate_keys

  def self.from_omniauth(auth, signed_in_resource = nil)
    identity = Identity.find_for_oauth(auth)

    user = signed_in_resource ? signed_in_resource : identity.user

    if user.nil?
      email = auth.info.email

      user = User.where(email: email).first if email

      if user.nil?
        user = User.new(name: auth.info.name.gsub(/\s+/, '_'),
                        email: auth.info.email,
                        # avatar: auth.info.image,
                        password: Devise.friendly_token[0,20])
        user.save!
      end
    end

    if identity.user != user
      identity.user = user
      identity.token = auth.credentials.token
      identity.refresh_token = auth.credentials.refresh_token
      identity.expires_at_unix = auth.credentials.expires_at
      identity.save!
    end

    user
  end

  def generate_keys
    begin
      self.build_api_access_token
      self.api_access_token.key = SecureRandom.urlsafe_base64(30).tr('_-', 'xx')
    end while ApiAccessToken.where(key: api_access_token.key).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/donate_events_controller.rb
class DonateEventsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    @donate_events = current_user.donate_events
  end

  def new
    @donate_event = current_user.donate_events.new
  end

  def create
    @donate_event = current_user.donate_events.new(donate_params)

    if @donate_event.save
      redirect_to donate_events_path
    else
      render :new
    end
  end

  def edit
    @donate_event = current_user.donate_events.find_by_token(params[:id])
  end

  def update
    @donate_event = current_user.donate_events.find_by_id(params[:id])

    if @donate_event.update(donate_params)
      redirect_to donate_events_path
    else
      render :edit
    end
  end

  def show
    token = params[:id]

    @donate_event = DonateEvent.find_by_token(token)

    @percentage = (@donate_event.total_amount.to_f / @donate_event.goal_amount.to_f) * 100

    gon.push({
      donate_event_token: token
    })

    render layout: "donate"
  end

  private

  def donate_params
    params.require(:donate_event).permit(:title, :goal_amount, :total_amount, :starting_amount, :end_after)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to new_user_session_path, alert: "無法獲得驗證！"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site:        "Donate Tool",
      description: "",
      keywords:    "",
      # og: {
      #   image: ActionController::Base.helpers.asset_path('logo.png')
      # },
      # fb: {
      #   app_id: "1304370673045470"
      # },
      reverse: true
    }
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning" }.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissible alert-<%= flash_class(key) %> fade show" role="alert">
      <%= value %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
<% end %>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to("Donate Tools", root_path, class: "navbar-brand") %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="d-flex navbar-nav me-auto mb-2 mb-lg-0"></ul>

      <div class="d-flex">
        <ul class="d-flex navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown no-arrow">
            <li class="nav-item dropdown">
              <% if user_signed_in? %>
              <li class="nav-item position-relative">
                <%= link_to "#", class: "nav-link" do %>
                  Hi, <%= current_user.name %>
                <% end %>
              </li>
              <li class="nav-item position-relative">
                <%= link_to donate_events_path, class: "nav-link" do %>
                  Donates
                <% end %>
              </li>
              <li>
                <%= link_to(destroy_user_session_path, method: :delete, class: "nav-link") do %>
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  登出
                <% end %>
              </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to("登入", new_user_session_path, class: "nav-link") %>
                </li>
              <% end %>
            </li>
          </li>
        </ul>
      </div>
  </div>
</nav>

app/views/donate_events/_form.html.erb
<div class="container">
  <%= simple_form_for(@donate_event) do |f| %>
    <%= f.input :title, label: "標題" %>
    <%= f.input :starting_amount, label: "初始金額" %>
    <%= f.input :goal_amount, label: "目標金額" %>
    <%= f.input :end_after, label: "結束日期" %>
    <%= f.submit "送出", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/donate_events/edit.html.erb
<%= render "form" %>

app/views/donate_events/index.html.erb
<%= link_to("建立", new_donate_event_path, class: "btn btn-primary") %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">標題</th>
      <th scope="col">初始金額</th>
      <th scope="col">當前金額</th>
      <th scope="col">目標金額</th>
      <th scope="col">創建日期</th>
      <th scope="col">結束日期</th>
      <th scope="col">#</th>
    </tr>
  </thead>
  <tbody>
    <% @donate_events.each do |donate_event| %>
    <tr>
      <td><%= link_to(donate_event.title, donate_event_path(donate_event.token), target: "_blank") %></td>
      <td><%= donate_event.starting_amount %></td>
      <td><%= donate_event.total_amount %></td>
      <td><%= donate_event.goal_amount %></td>
      <td><%= donate_event.created_at %></td>
      <td><%= donate_event.end_after %></td>
      <td><%= link_to("編輯", edit_donate_event_path(donate_event.token)) %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/donate_events/new.html.erb
<div class="container">
  <%= simple_form_for(@donate_event) do |f| %>
    <%= f.input :title, label: "標題" %>
    <%= f.input :starting_amount, label: "初始金額" %>
    <%= f.input :goal_amount, label: "目標金額" %>
    <%= f.input :end_after, label: "結束日期" %>
    <%= f.submit "送出", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/donate_events/show.html.erb
<style>
  .condensed__container {
    width: 100%;
    position: relative;
    overflow: hidden;
    box-shadow: 0 0 3px #222;
  }
  .condensed__current__amount {
    height: 100%;
    width: 100%;
    position: absolute;
    top: 0px;
    left: 0px;
    z-index: 11;
    text-align: center;
    vertical-align: middle;
  }
  .condensed__title {
      position: absolute;
      top: 0px;
      left: 10px;
      text-shadow: 0px 0px 1px rgb(34 34 34);
  }
  .condensed__amount {
      position: absolute;
      top: 0px;
      right: 10px;
      text-shadow: 0px 0px 1px rgb(34 34 34);
  }
  .condensed__bar {
      height: 100%;
      position: absolute;
      top: 0px;
      left: 0px;
      z-index: 9;
      box-shadow: 0px 0px 1px rgb(0 0 0);
  }
</style>


<div>
  <div style="padding: 10px 20px;">
    <div class="condensed__container" style="height: 44px; background: rgb(221, 221, 221);">
      <div class="condensed__current__amount" style="color: rgb(0, 0, 0); font: 800 22px / 44px Ubuntu;">
        <div id="total_amount"> <%= @donate_event.total_amount %></div>

        <div class="condensed__title" style="color: rgb(0, 0, 0); font: 800 22px / 44px Ubuntu;">
          <%= @donate_event.title %>
        </div>
        <div class="condensed__amount" style="color: rgb(0, 0, 0); font: 800 22px / 44px Ubuntu;">
          <div id="goal_amount"> <%= @donate_event.goal_amount %></div>
        </div>
      </div>

      <div style="height: 100%; width: 100%; position: absolute; top: 0px; left: 0px; z-index: 10; box-shadow: rgb(0, 0, 0) 0px 0px 2px inset;">
      </div>

      <div id="progress-bar" class="donation-bar condensed__bar" style="background: linear-gradient(transparent, rgba(0, 0, 0, 0.15)) rgb(245, 228, 98); width: <%= "#{@percentage}%" %>;">
      </div>
    </div>
  </div>

  <div class="col-md-12" style="padding-top: 170px;
    padding-left:200px;">
    <lottery></lottery>
  </div>
</div>

app/views/home/index.html.erb
<style>
  .condensed__container {
    width: 100%;
    position: relative;
    overflow: hidden;
    box-shadow: 0 0 3px #222;
  }
  .condensed__current__amount {
    height: 100%;
    width: 100%;
    position: absolute;
    top: 0px;
    left: 0px;
    z-index: 11;
    text-align: center;
    vertical-align: middle;
  }
  .condensed__title {
      position: absolute;
      top: 0px;
      left: 10px;
      text-shadow: 0px 0px 1px rgb(34 34 34);
  }
  .condensed__amount {
      position: absolute;
      top: 0px;
      right: 10px;
      text-shadow: 0px 0px 1px rgb(34 34 34);
  }
  .condensed__bar {
      height: 100%;
      position: absolute;
      top: 0px;
      left: 0px;
      z-index: 9;
      box-shadow: 0px 0px 1px rgb(0 0 0);
  }
</style>

<% if @donate_event.present? %>
<div>
  <div style="padding: 10px 20px;">
    <div class="condensed__container" style="height: 44px; background: rgb(221, 221, 221);">
      <div class="condensed__current__amount" style="color: rgb(0, 0, 0); font: 800 22px / 44px Ubuntu;">
        <div id="total_amount"> <%= @donate_event.total_amount %></div>

        <div class="condensed__title" style="color: rgb(0, 0, 0); font: 800 22px / 44px Ubuntu;">
          <%= @donate_event.title %>
        </div>
        <div class="condensed__amount" style="color: rgb(0, 0, 0); font: 800 22px / 44px Ubuntu;">
          <div id="goal_amount"> <%= @donate_event.goal_amount %></div>
        </div>
      </div>

      <div style="height: 100%; width: 100%; position: absolute; top: 0px; left: 0px; z-index: 10; box-shadow: rgb(0, 0, 0) 0px 0px 2px inset;">
      </div>

      <div id="progress-bar" class="donation-bar condensed__bar" style="background: linear-gradient(transparent, rgba(0, 0, 0, 0.15)) rgb(51, 102, 153); width: <%= "#{@percentage}%" %>;">
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= Gon::Base.render_data %>
    <%= display_meta_tags(default_meta_tags) %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render "common/google_analytics" if Rails.env.production? %>
  </head>

  <body>
    <%= render "common/navbar" %>

    <div class="container-fluid">
      <%= render "common/flashes" %>
      <%= yield %>
    </div>

      <%= render "common/footer" %>
  </body>
</html>

app/views/layouts/donate.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= Gon::Base.render_data %>
    <%= display_meta_tags(default_meta_tags) %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= render "common/google_analytics" if Rails.env.production? %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>